-- Audit chain integrity: one chain per workspace, a hash that covers every field, idempotent
-- delivery, the filters an auditor needs, and a table the application cannot edit.
--
-- V1 wrote one chain for the whole platform and hashed only some of each row. Those rows stay as
-- they are, labelled hash_version 1, and keep verifying under the formula they were written with.
-- Every row written from here on is hash_version 2 and joins the chain of its own workspace (or the
-- 'platform' chain, for events that belong to no workspace), which is what lets a workspace verify
-- and export its own history without being shown anyone else's.

ALTER TABLE audit_events
    ADD COLUMN hash_version SMALLINT NOT NULL DEFAULT 1,
    ADD COLUMN chain_key    TEXT,
    -- Generated by the sender before the first attempt, so a delivery retried after a timeout is
    -- recognised and answered with the entry already written instead of being appended twice.
    ADD COLUMN event_uuid   UUID UNIQUE;

-- Version 1 rows are labelled with the chain they belong to, so the first version 2 entry of a
-- workspace links to that workspace's last older entry rather than starting a second history.
-- Run before the trigger below exists: after it, no row can be changed at all.
UPDATE audit_events SET chain_key = COALESCE(org_id::text, 'platform');

ALTER TABLE audit_events
    ADD CONSTRAINT audit_hash_version_valid CHECK (hash_version IN (1, 2)),
    ADD CONSTRAINT audit_chain_key_present CHECK (hash_version = 1 OR chain_key IS NOT NULL);

-- A locked account is its own outcome: it is neither a plain failure nor a policy refusal, and an
-- auditor filtering for it should not have to read every failed sign-in.
ALTER TABLE audit_events DROP CONSTRAINT audit_outcome_valid;
ALTER TABLE audit_events
    ADD CONSTRAINT audit_outcome_valid CHECK (outcome IN ('succeeded', 'failed', 'denied', 'locked'));

-- The database refuses a second entry linked to the same predecessor. Appends are serialised with
-- an advisory lock; this is the backstop that turns a forked chain into a failed insert, which is
-- retried, instead of a silent break found weeks later. Version 1 rows are left out: the old
-- global chain already holds a fork from before the lock existed.
CREATE UNIQUE INDEX audit_chain_link_unique ON audit_events (chain_key, previous_hash)
    WHERE hash_version >= 2;
-- NULL is never equal to NULL, so the index above cannot stop a second start of the same chain.
CREATE UNIQUE INDEX audit_chain_genesis_unique ON audit_events (chain_key)
    WHERE hash_version >= 2 AND previous_hash IS NULL;

-- Walking a chain in order, and finding where it ends.
CREATE INDEX audit_chain_sequence_idx ON audit_events (chain_key, sequence);
CREATE INDEX audit_legacy_sequence_idx ON audit_events (sequence) WHERE hash_version = 1;

-- Every filter the audit log offers starts with the workspace, so a search never reads another's
-- rows. audit_org_time_idx from V1 already covers (org_id, occurred_at DESC). The two indexes V1
-- made on actor and action alone are not tenant-scoped, nothing queries them that way, and each
-- slows every append.
DROP INDEX audit_actor_idx;
DROP INDEX audit_action_idx;
CREATE INDEX audit_org_sequence_idx ON audit_events (org_id, sequence DESC);
CREATE INDEX audit_org_action_idx ON audit_events (org_id, action);
CREATE INDEX audit_org_actor_idx ON audit_events (org_id, actor_id);
CREATE INDEX audit_org_resource_idx ON audit_events (org_id, resource_type, resource_id);
CREATE INDEX audit_org_outcome_idx ON audit_events (org_id, outcome);

-- Append-only, enforced where the application cannot reach around it. REVOKE in V1 does not bind
-- the role that owns the table, which is the role this service connects as; a trigger binds
-- everyone, so an UPDATE or DELETE from the application, an ORM, a script or a console fails with
-- an error instead of quietly rewriting history. The table's owner can still drop the trigger,
-- which is why the log is also hash-chained: dropping it and editing a row breaks the chain.
CREATE FUNCTION audit_events_append_only() RETURNS trigger
    LANGUAGE plpgsql AS
$$
BEGIN
    RAISE EXCEPTION 'audit_events is append-only: % is not allowed', TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$;

CREATE TRIGGER audit_events_no_change
    BEFORE UPDATE OR DELETE ON audit_events
    FOR EACH ROW EXECUTE FUNCTION audit_events_append_only();

-- TRUNCATE does not fire row triggers, and would empty the log in one statement.
CREATE TRIGGER audit_events_no_truncate
    BEFORE TRUNCATE ON audit_events
    FOR EACH STATEMENT EXECUTE FUNCTION audit_events_append_only();
